### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by JsPeanut**

### CODE REVIEW

**Comment by JsPeanut** [comment]
Hello there! I have a question:

In the project, I didn't add any validation for the To do's name, so I was thinking of these:

1. Add validation with JS
2. Add validation with Data Annotations (but, at least what i think is, this would imply creating a To do model in the main project, adding an asp-for tag in the To do name input tags so the To do object is later validated, then in the controller add methods for post, put and delete requests (with RestSharp), that would later be executed after the user clicks on the corresponding button.

Which is best practice?

**Comment by TheCSharpAcademy** [comment]
@JsPeanut I'm approving the project as it does what it's supposed to do, but when use MVC/Blazor/Razor Pages I'd leave javascript only for the stuff that can't be done using razor syntax. Javascript is messy and hard to debug. By using so much javascript you under-use the best that Asp.NET has to offer: strongly-typed, easy to debug code. You're giving that up in exchange for spaghetti. 😁

Also, you could create the API and the UI within one project. You'd only create a separate project in case more than one app was calling the api. 

But regardless, well done on completing the project You showed nice command of JS.

**Comment by JsPeanut** [comment]
Hey! You're right. I thought I could only manage the CRUD logic with JavaScript. Now I replaced the JS logic. Thanks for the feedback!

**Comment by JsPeanut** [comment]
> Hey! You're right. I thought I could only manage the CRUD logic with JavaScript. Now I replaced the JS logic. Thanks for the feedback!

Also I added validation, forgot to say

**Pull request merged**
