### PR TITLE
Merge Request :)

### PR DESCRIPTION
**Pull request by K-MYR**
Hey!

I hope you have a great day!
In this project for the first time i played around with animations in js and i am eager to try out more complex animations in my next projects!
As always thank you for reviewing my code! :) ....and please be brutal in your review XD

Cheers!

(Steps before running the app: Inside "Appsettings.json": Configure the SQL Server Connection String; Auto-migrate: if true migrates the database automatically to the server on startup; SeedData: if true seeds data into the database on startup if the table is empty;)

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@K-MYR Thanks for submitting!  Did everything work out well for you? I'm getting a bunch of errors, including the web requests, and the data isn't being saved.
image

Also do I need to do a npm install somewhere? Your bootstrap seems to be inside a node_modules folder, which I couldn't find:

image

**Comment by K-MYR** [comment]
todoui

yeah for me everythings works! ;/

**Comment by K-MYR** [comment]
@TheCSharpAcademy oh i see whats the problem, my bad! sry i m not very familiar with npm; i used npm to install node_modules into the lib folder inside wwwroot. I thought they would be automatically included in the project, but i guess they are ignored by default to keep the repository size small.....i guess i should include them in the repository for the code reviews?

**Comment by TheCSharpAcademy** [comment]
@K-MYR Could you please delete your node_modules file, restore it, and let me know how to get it to work?  I'm asking because node_modules wasn't pushed to the repository (and it shouldn't) but I've never had to restore it inside an ASP.NET Core app 😁 Unfortunately I don't have time to find out 😆

**Comment by K-MYR** [comment]
@TheCSharpAcademy i ll try that. no worries!

**Comment by K-MYR** [comment]
@TheCSharpAcademy okay i tested it with a new clone of my repo so this should work for you:

the solution explorer should look like this:
fixtodo1

in my solution you see the following: dependencies -> npm (www\lib\package.json) -> js dependencies
fixtodo2
right click "npm (www\lib\package.json)" and click restore packages
after a few seconds the node_modules folder with the npm packages should be now be inside the wwwwroot/lib folder

sry for the inconvenience! for the future: should i do something different to make things easier for you? i wanted to have the latest bootstrap and some extra packages for animation and validation and thought its fine if they are in the node_modules folder
i hope everythings works now on your end!
thanks for your time! :)

**Comment by TheCSharpAcademy** [comment]
@K-MYR no that's all good. This is a first for me and it's not very common so no worries. Usually I need to do a "npm install" in React/Angular projects but I never had to do it in an asp.net core project. I'll proceed with the review now 😁. And no, never commit the node_modules folder, it's like 5 million giga bytes large

**Comment by K-MYR** [comment]
>And no, never commit the node_modules folder, it's like 5 million giga bytes large

@TheCSharpAcademy okay good to know XD

**Comment by TheCSharpAcademy** [comment]
@K-MYR Works perfectly now, this one is going to feature in our Linkedin page if you don't mind. You should have your profile linked to us there so I can tag you 😁

**Comment by K-MYR** [comment]
@TheCSharpAcademy I dont mind at all! There are a few things that could be improved. But if you want to feature the project, i would appreciate it! ^^ i just made a linkedin profile and linked it to the c#academy :)
thanks for the review btw 👍

**Comment by TheCSharpAcademy** [comment]
@K-MYR I'm not sure why but when clicking on: www.linkedin.com/in/konstantin-mayer-6468272ab I get this: 
image

**Comment by K-MYR** [comment]
@TheCSharpAcademy  i dont know how, but it changed somehow....i edited it and updated my profile. it should work now!

**Pull request merged**
