### PR TITLE
Finished for review

### PR DESCRIPTION
**Pull request by ManuelE-Osorio**
Also kinda simple project. Spent more time messing with styling. Kinda happy with the end result. More information on main repo: https://github.com/ManuelE-Osorio/ASP.NET-MVC-Todo-List

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@ManuelE-Osorio I'm having trouble running the app, does it work for you? The server seems to be running but the page won't load. If it's working for you, could you please send a quick video demonstrating the requirements? Thank you.

image

**Comment by ManuelE-Osorio** [comment]
@TheCSharpAcademy  I think you are opening the API address. I have the html file in the TodoListWebPage folder, I'm not sure if its okay like this.
https://github.com/TheCSharpAcademy/CodeReviews.MVC.Todo/assets/147839063/801765a9-be0f-4ba4-b78c-e67279e3a5a2

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@ManuelE-Osorio I see now. I was expecting an ASP.NET Core MVC project but I guess since wasn't a requirement, I'll accept the api instead.

It's looking good, well done! 😎But these two requirements are missing 😢

image

**Comment by ManuelE-Osorio** [comment]
@TheCSharpAcademy  Sorry, I was a little confused with the requirements because in the Microsoft Documentation, they don't use MVC to build a Minimal API. I don't know how I've missed those two requirements, anyway they have been submitted now.

**Pull request merged**
